random_seed: 1
rollout_length: 2000
batch_size: 16
num_batches: 1
deter: False
save_pos: True
save_frequency: 100
model_dir: ${oc.env:MODEL_DIR}/chain_gns
save_dir: ${model_dir}

ld_kwargs:
  step_per_sigma: 5
  step_size: 0.0001

data:
  _target_: graphwm.data.Tip3pDataset
  directory: ${oc.env:TIP3P_TEST_DATASET_DIR}
  split: ${oc.env:PROJECT_ROOT}/splits/tip3p/test.txt
  mode: rollout
  recursive_metis: False

hydra:
  run:
    dir: ${save_dir}
