# log frequency
# val_check_interval: 5000
check_val_every_n_epoch: 1
progress_bar_refresh_rate: 10

wandb:
  name: ${expname}
  group: ${expname}
  save_dir: ${workdir}
  project: mlcgmd
  entity: null
  log_model: True
  mode: 'online'

wandb_watch:
  log: 'all'
  log_freq: 1000

lr_monitor:
  logging_interval: "step"
  log_momentum: False
